### ISSUE TITLE
Fail test

### ISSUE THREAD

**Issue by kheyro** [learn-co-curriculum/returning-string-data#11]
Tests fail because seeded post doesn't have author.
And spec, expect `title`, `description`, `submit post` field in new post form, but it is `post[title]`, `post[description` and `Create Post`.
Also in routes.rb it misses the `:update` action

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @kheyro.

We have updated the materials and removed the tests from this lesson as they were not aligned with the readme content and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
