### ISSUE TITLE
Test do not reflect objectives

### ISSUE THREAD

**Issue by efl7a** [learn-co-curriculum/returning-string-data#12]
As stated above, the tests have issues, but more importantly, they do not reflect the point of this lab.  Also, it would have been great if you showed how to add this into a js file instead of inserting it in the html file.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @efl7a.

We have updated the materials and removed the tests from this lesson as they were not aligned with the readme content and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
