### ISSUE TITLE
Update Rails Gem

### ISSUE THREAD

**Issue by dwyn** [learn-co-curriculum/returning-string-data#13]
I used 4.2.8 and that seemed to do the trick. 
With 4.2.5, I received:
`Array values in the parameter to `Gem.paths=` are deprecated.
Please use a String or nil.
An Array ({"GEM_PATH"=>["/Users/dwyn/.rvm/gems/ruby-2.5.0", "/Users/dwyn/.rvm/gems/ruby-2.5.0@global"]}) was passed in from bin/rake:3:in `load'
Could not find json-1.8.3 in any of the sources`

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @dwyn .

We have updated the materials to prevent this error from occurring and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
