### ISSUE TITLE
Tests don't match lesson content. 

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/returning-string-data#14]
This is a codealong, without any directions to do additional lab-like work, and yet the tests expect it.If this is the intention, you should add a few lines at the end (Hey, the tests will ask you to patch things up a bit, to keep you in practice with Rails). Or create tests that match the codealong and leave it at that. 

Thanks!

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @MiriamPeskowitz.

We have updated the materials and removed the tests from this lesson as they were not aligned with the readme content and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
