### ISSUE TITLE
Last 2 tests for submit buttons(new and edit)

### ISSUE THREAD

**Issue by aisayo** [learn-co-curriculum/returning-string-data#15]
The last two tests will fail because of the partial. Student will get a failure that "Update post" and "Submit post" are undefined. This is because of the partial, _form.rb. The partial doesnt allow for customization of two different submit buttons. 

The solution is to extract ONLY the following from _form.rb and add to both the new and edit views:
<%= form_for(@post) do |f| %>

 <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

then render the partial in both new and edit views like so(you need to add a local to define f inside the partial:

<%= form_for(@post) do |f| %>
<%= render "form", f: f %>
 <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

now student can customize the submit button text.

Make sure to add ":update" to posts resources in config/routes for get PATCH path

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @aisayo.

We have updated the materials and removed the tests from this lesson as they were not aligned with the readme content and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
