### ISSUE TITLE
test issues

### ISSUE THREAD

**Issue by ALTR8** [learn-co-curriculum/returning-string-data#4]
The tests were unpassable if just following the code-along directly

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @ALTR8.

We have updated the materials and removed the tests from this lesson as they were not aligned with the readme content and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
