### ISSUE TITLE
test seeks 'title', error: "unable to find field "title"

### ISSUE THREAD

**Issue by smithWEBtek** [learn-co-curriculum/returning-string-data#7]
in: 
rspec ./spec/features/post_spec.rb

changed the test as follows: 
existing: 
    fill_in 'title', with: "My post title"
    fill_in 'description', with: "My post description"
    click_on "Submit Post"

changed to: 
    fill_in 'post_title', with: "My post title"
    fill_in 'post_description', with: "My post description"
    click_on "Create Post"

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @smithWEBtek.

We have updated the materials and removed the tests from this lesson as they were not aligned with the readme content and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
