### ISSUE TITLE
ReadMe Code works in browser but all tests fail

### ISSUE THREAD

**Issue by hansenjl** [learn-co-curriculum/returning-string-data#8]
2 students have now asked about this ReadMe - It works in the browser but the tests don't pass. I ran my own copy of it off my github and got the same result. I also ran the student's copy in the virtual IDE to make sure it wasn't a local environment issue and got the same result.  

navigate shows the title on the show page in a h1 tag
Failure/Error: <%= @post.author.name %>

ActionView::Template::Error:
undefined method `name' for nil:NilClass

navigate to post pages
Failure/Error: <%= @post.author.name %>

ActionView::Template::Error:
undefined method `name' for nil:NilClass

navigate shows the description on the show page in a p tag
Failure/Error: <%= @post.author.name %>

ActionView::Template::Error:
undefined method `name' for nil:NilClass

form shows a new form that submits content and redirects and prints out params
Failure/Error: fill_in 'title', with: "My post title"

Capybara::ElementNotFound:
Unable to find field "title"

form shows a new form that submits content and redirects and prints out params
Failure/Error: click_on "Update Post"

ActionController::RoutingError:
No route matches [PATCH] "/posts/1"

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @hansenjl.

We have updated the materials and removed the tests from this lesson as they were not aligned with the readme content and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
